### ISSUE TITLE
Can't install near-sandbox on WSL2

### ISSUE THREAD

**Issue by ChaoticTempest** [near/sandbox#2]
Seems like when trying to install the `near-sandbox` on WSL2, I'm running into some issues:
```
❯ near-sandbox
Downloading release from https://cloudflare-ipfs.com/ipfs/QmZ6MQ9VMxBcahcmJZdfvUAbyQpjnbHa9ixbqnMTq2k8FG/Linux-near-sandbox.tar.gz
near-sandbox has been installed!
/usr/local/lib/node_modules/near-sandbox/run.js:27
          throw new Error("binary failed to be installed to " + binPath);
          ^

Error: binary failed to be installed to /usr/local/lib/node_modules/near-sandbox/node_modules/binary-install/bin/bin/near-sandbox
```

Looks like the path `[...]/bin/bin` is the problem since I have it under `[...]/bin/near-sandbox` but not `[...]/bin/bin/near-sandbox`.

Digging a bit deeper, this line of code seems to be the problematic one:
```
const binPath = join(binary.installDirectory, "bin", binary.name);
```
where `binary.installDirectory = "/usr/local/lib/node_modules/near-sandbox/node_modules/binary-install/bin"`

**Comment by willemneal** [comment]
Yep. I updated versions of binary-install and somehow didn't bite me until now.
