### ISSUE TITLE
Allow user to override version of sandbox binary

### ISSUE THREAD

**Issue by austinabell** [near/sandbox#26]
Currently, the master branch with a specific commit is used for the `bin_url`, but it would be beneficial if a user could override this with their own URL or just be able to customize the commit/version to be able to test against older/newer versions.

Ideally using this env variable (or helper function) would overwrite the existing binary if one already exists instead of skipping checks if the binary is already installed.

**Comment by mohamedalichelbi** [comment]
By removing the commit hash from [this line](https://github.com/near/sandbox/blob/9cbfce765f75b70db59001770db3477e6e6aefcc/npm/dist/getBinary.js#L17) I got the latest binary (1.25.0) even though mainnet is on 1.24.0
I think ideally integration tests should run whatever is live on mainnet per default, but I agree that ability to control this would be very helpful
