### ISSUE TITLE
Error: Unsupported platform: Darwin arm64

### ISSUE THREAD

**Issue by 0xrinegade** [near/sandbox#35]
Any plans on supporting Apple M1 Chip?

**Comment by ChaoticTempest** [comment]
It's currently being worked on right now. Sandbox binaries aren't available for M1 quite yet. You can track the progress in this issue: https://github.com/near/workspaces-rs/issues/110

**Comment by bulbazavr1024** [comment]
@PabloLION Hey, can you share code, where you can start ava tests on M1 Chip

**Comment by PabloLION** [comment]
> @PabloLION Hey, can you share code, where you can start ava tests on M1 Chip

I disabled ava test to run `yarn`

**Comment by bulbazavr1024** [comment]
@PabloLION you suggested do separate brunch for m1. Can you do it or how can I support you to do it ?

**Comment by PabloLION** [comment]
I have had it for some repos of [@near-examples](https://github.com/near-examples), just disabling the things mentioned above. If you want I can share with you. What do you need? @bulbazavr1024

**Comment by bulbazavr1024** [comment]
@PabloLION readme file with step by step instructions, sir, if u can

**Comment by PabloLION** [comment]
@bulbazavr1024 I still don't know which repo you want. But to be clear, this is not a fix but a work-around to disable the functions. 

I did only 2 things: 

1. remove the `near-workspaces` dependencies from `package.json`
2. remove all `.ava.ts` files

**Comment by rocalex** [comment]
Same error.
```
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to run build scripts

error: Unsupported platform
  --> /Users/rocalex/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sandbox-utils-0.2.0/src/lib.rs:24:5
   |
24 |     compile_error!("Unsupported platform");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


error[E0308]: mismatched types
  --> /Users/rocalex/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sandbox-utils-0.2.0/src/lib.rs:13:24
   |
13 | const fn platform() -> &'static str {
   |          --------      ^^^^^^^^^^^^ expected `&str`, found `()`
   |          |
   |          implicitly returns `()` as its body has no tail or `return` expression


error: aborting due to 2 previous errors


For more information about this error, try `rustc --explain E0308`.

error: could not compile `near-sandbox-utils` due to 3 previous errors

```

**Comment by ChaoticTempest** [comment]
This is now resolved with https://github.com/near/sandbox/pull/44 and workspaces-rs `0.4.0` now works with M1
